# -*- coding: utf-8 -*-
"""Copy of phi3-finance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PgV1vr5FnpbzvCzG85QGfniuzayXjB_c
"""

# Consolidated installations for Unsloth in Colab
# Install Unsloth's Colab-optimized version, which handles its own dependencies
# The `--no-deps` flag prevents pip from reinstalling core packages like torch,
# allowing Unsloth to manage its specific dependency versions.
!pip install --no-deps "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"
# Optionally, if xformers is needed for faster attention and not installed by unsloth, install/upgrade it.
# !pip install xformers trl --upgrade

!pip install unsloth_zoo

from unsloth import FastLanguageModel

# Load model directly using unsloth
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="priyalchugh06/phi3-finance",
    max_seq_length=2048, # A common default for max sequence length
    dtype=None,          # Auto-detects based on system (e.g., bfloat16 for supported GPUs)
    load_in_4bit=True    # Load in 4-bit for memory efficiency
)

FastLanguageModel.for_inference(model)
print("✓ Model loaded from HF using Unsloth")

prompt = "### Instruction:\nWhat is dollar cost averaging?\n\n### Response:\n"
inputs = tokenizer(prompt, return_tensors="pt").to("cuda")
outputs = model.generate(**inputs, max_new_tokens=100, temperature=0.5,
                         do_sample=True, pad_token_id=tokenizer.eos_token_id)
print(tokenizer.decode(outputs[0], skip_special_tokens=True))

FastLanguageModel.for_inference(model)
print("Model in inference mode")

from transformers import TextStreamer

def ask(question, context="", max_tokens=200, temperature=0.7):
  if context.strip():
    prompt=f"### Instruction:\n{question}\n\n### Input:\n{context}\n\n### Response:\n"
  else:
    prompt = f"### Instruction:\n{question}\n\n### Response:\n"
  inputs = tokenizer(prompt, return_tensors="pt").to("cuda")

  streamer = TextStreamer(tokenizer, skip_prompt=True, skip_special_tokens=True)

  model.generate(
      **inputs,
        streamer=streamer,
        max_new_tokens=max_tokens,
        temperature=temperature,
        do_sample=True,
        pad_token_id=tokenizer.eos_token_id,
  )

ask("What is the difference between a Roth IRA and a traditional IRA?")

base_model, base_tokenizer = FastLanguageModel.from_pretrained(
    model_name="unsloth/Phi-3-mini-4k-instruct-bnb-4bit",
    max_seq_length=256,
    dtype=None,
    load_in_4bit=True,
)
FastLanguageModel.for_inference(base_model)

question = "Should I invest in index funds or pick individual stocks?"
prompt   = f"### Instruction:\n{question}\n\n### Response:\n"
inputs   = base_tokenizer(prompt, return_tensors="pt").to("cuda")

print("── BASE MODEL ───────────────────────────────────────")
base_streamer = TextStreamer(base_tokenizer, skip_prompt=True, skip_special_tokens=True)
base_model.generate(**inputs, streamer=base_streamer, max_new_tokens=150,
                    temperature=0.7, do_sample=True,
                    pad_token_id=base_tokenizer.eos_token_id)

print("\n── FINE-TUNED ───────────────────────────────────────")
inputs = tokenizer(prompt, return_tensors="pt").to("cuda")
ft_streamer = TextStreamer(tokenizer, skip_prompt=True, skip_special_tokens=True)
model.generate(**inputs, streamer=ft_streamer, max_new_tokens=150,
               temperature=0.7, do_sample=True,
               pad_token_id=tokenizer.eos_token_id)

!pip install -q rouge-score bert-score

import torch
import time
import numpy as np
from rouge_score import rouge_scorer
from bert_score import score as bert_score

test_questions = [
    "Should I invest in index funds or pick individual stocks?",
    "What is dollar cost averaging?",
    "Should I pay off debt or invest first?",
    "What is the difference between a Roth IRA and a traditional IRA?",
    "How much should I have in an emergency fund?",
    "What is compound interest?",
    "How does capital gains tax work?",
    "Is it worth paying a financial advisor?",
    "What credit score do I need to buy a house?",
    "What happens to my stocks if my broker goes bankrupt?",
]

def generate(mdl, tok, question, max_tokens=150):
    prompt = f"### Instruction:\n{question}\n\n### Response:\n"
    inputs = tok(prompt, return_tensors="pt").to("cuda")

    torch.cuda.synchronize()
    start = time.perf_counter()

    with torch.no_grad():
        output = mdl.generate(
            **inputs,
            max_new_tokens=max_tokens,
            temperature=0.7,
            do_sample=True,
            pad_token_id=tok.eos_token_id,
        )

    torch.cuda.synchronize()
    elapsed_ms = (time.perf_counter() - start) * 1000


    generated = tok.decode(
        output[0][inputs["input_ids"].shape[1]:],
        skip_special_tokens=True
    ).strip()

    return generated, elapsed_ms

print("Generating from BASE model...")
base_answers  = []
base_times    = []
for q in test_questions:
    ans, ms = generate(base_model, base_tokenizer, q)
    base_answers.append(ans)
    base_times.append(ms)
    print(f"  ✓ {q[:50]}...")

print("\nGenerating from FINE-TUNED model...")
ft_answers = []
ft_times   = []
for q in test_questions:
    ans, ms = generate(model, tokenizer, q)
    ft_answers.append(ans)
    ft_times.append(ms)
    print(f"  ✓ {q[:50]}...")

