# -*- coding: utf-8 -*-
"""finetuning-phi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ggLvcO5mPVMkQnrjguQYZ06-XMHIHNAH
"""

!pip install -q transformers datasets peft accelerate bitsandbytes trl \
             sentencepiece pandas pyarrow huggingface_hub wandb

from google.colab import userdata
from huggingface_hub import login

HF_TOKEN = userdata.get('HF_TOKEN')
login(token=HF_TOKEN)
print("Logged in to HuggingFace")

from datasets import load_dataset

ds = load_dataset("gbharti/finance-alpaca")

# Cell 5 — load dataset and save to Drive
from datasets import load_dataset

dataset = load_dataset("gbharti/finance-alpaca", split="train")
dataset.to_parquet("/content/drive/MyDrive/mistral-finance-ft/data/finance_alpaca_raw.parquet")
print(f"Saved {len(dataset):,} rows")

import pandas as pd
df = pd.read_parquet("/content/drive/MyDrive/mistral-finance-ft/data/finance_alpaca_raw.parquet")
print(f"Loaded {len(df):,} rows")

print(df.shape)
print(df.head(3))

print(df.dtypes)
print(df.isnull().sum())

df.iloc[15]

df["instruction_words"] = df["instruction"].str.split().str.len()

print(df["instruction_words"].describe())

df.iloc[10]

df["instr_words"]  = df["instruction"].str.split().str.len()
df["input_words"]  = df["input"].str.split().str.len().fillna(0).astype(int)
df["output_words"] = df["output"].str.split().str.len()

df["total_tokens"] = ((df["instr_words"] + df["input_words"] + df["output_words"])/0.75).astype(int)

print("--length stats--")
print(df[["instr_words", "input_words", "output_words", "total_tokens"]].describe().round(1))


for limit in [256, 512, 1024, 2048]:
  pct = (df["total_tokens"] <=limit).mean() * 100
  print(f" max_seq_length={limit:4d} -> covers {pct:.1f}% of examples")

df[df['input'].isna()]

TOPIC_KEYWORDS = {
    "investing":    ["invest", "portfolio", "etf", "fund", "index", "dividend", "return", "asset", "diversif"],
    "stocks":       ["stock", "share", "equity", "market", "trading", "option", "put", "call", "short", "nyse", "nasdaq"],
    "tax":          ["tax", "irs", "deduct", "capital gain", "w-2", "1099", "refund", "bracket", "fica"],
    "debt":         ["debt", "loan", "mortgage", "interest rate", "pay off", "borrow", "credit card", "student loan"],
    "retirement":   ["401k", "ira", "roth", "pension", "retire", "rmd", "social security"],
    "credit":       ["credit score", "credit report", "fico", "utilization", "credit card", "credit limit"],
    "real estate":  ["house", "home", "property", "real estate", "rent", "landlord", "mortgage"],
    "banking":      ["bank", "savings account", "checking", "fdic", "interest", "wire transfer", "routing"],
}

def label_topic(text):
  text = text.lower()
  for topic, keywords in TOPIC_KEYWORDS.items():
    if any(kw in text for kw in keywords):
      return topic
  return "other"

df["topic"] = (df["instruction"] + " " + df["output"]).apply(label_topic)
print("Topic Distribution")
print(df["topic"].value_counts())

df.drop(['instruction_words'], inplace=True, axis=1)

df.head(5)

dupes = df["instruction"].duplicated()
print(f"\nDuplicate instructions : {dupes.sum()} rows")

import matplotlib.pyplot as plt
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import seaborn as sns
from datasets import load_dataset
from collections import Counter
from wordcloud import WordCloud
import re
import warnings
warnings.filterwarnings("ignore")

fig = plt.figure(figsize=(16, 12))
fig.suptitle("finance-alpaca Dataset Analysis", fontsize=16, fontweight="bold", y=0.98)
gs = gridspec.GridSpec(2, 3, figure=fig, hspace=0.4, wspace=0.35)


ax1 = fig.add_subplot(gs[0, 0])
df["output_words"].clip(upper=600).hist(bins=40, ax=ax1, color="#378ADD", edgecolor="white")
ax1.axvline(df["output_words"].median(), color="#D85A30", linestyle="--", label=f"Median: {int(df['output_words'].median())}w")
ax1.set_title("Output length (words)")
ax1.set_xlabel("Word count")
ax1.set_ylabel("Rows")
ax1.legend()

# Plot 2 — Instruction word count
ax2 = fig.add_subplot(gs[0, 1])
df["instr_words"].clip(upper=80).hist(bins=30, ax=ax2, color="#1D9E75", edgecolor="white")
ax2.axvline(df["instr_words"].median(), color="#D85A30", linestyle="--", label=f"Median: {int(df['instr_words'].median())}w")
ax2.set_title("Instruction length (words)")
ax2.set_xlabel("Word count")
ax2.set_ylabel("Rows")
ax2.legend()

print("Quality checks")

short = df['output_words'] < 5
print(f"Outputs under 5 words: {short.sum()} rows")
print(df[short][["instruction", "output"]].head(5).to_string())


long = df["output_words"] > 500
print(f"\nOutputs over 500 words: {long.sum()} rows")


#duplicated
dupes = df["instruction"].duplicated()
print(f"\nDuplicate instructions: {dupes.sum()} rows")
print(df[dupes][["instruction", "output"]].head(5).to_string())

df['instruction'].describe()

def is_finance(row):
    text = (row["instruction"] + " " + row["output"]).lower()
    return any(kw in text for kw in [
        "stock","bond","invest","portfolio","dividend","equity","fund","market",
        "tax","retire","asset","debt","loan","mortgage","interest","credit","bank",
        "401k","ira","roth","income","saving","budget","insurance","option","share"
    ])

def format_for_training(row):
    if row["input"].strip():
        return (f"### Instruction:\n{row['instruction']}\n\n"
                f"### Input:\n{row['input']}\n\n"
                f"### Response:\n{row['output']}")
    return (f"### Instruction:\n{row['instruction']}\n\n"
            f"### Response:\n{row['output']}")

# Apply filters
clean = df.copy()
clean = clean[clean.apply(is_finance, axis=1)]           # keep finance rows
clean = clean[clean["output_words"] >= 5]                # remove near-empty outputs
clean = clean[clean["total_tokens"] <= 1024]             # Fits in 1024 tokens (updated)
clean = clean.drop_duplicates(subset="instruction")      # remove duplicate questions
clean = clean.sample(n=5000, random_state=42)            # Sample to reduce dataset size
clean["text"] = clean.apply(format_for_training, axis=1)

print(f"\n=== CLEAN DATASET ===")
print(f"Original : {len(df):,} rows")
print(f"After filter : {len(clean):,} rows ({len(clean)/len(df)*100:.1f}% kept)")
print(f"\nSample formatted example:")
print(clean["text"].iloc[0])

# Save for training
clean[["instruction","input","output","text","topic"]].to_parquet("finance_alpaca_clean.parquet", index=False)
print("\nSaved to finance_alpaca_clean.parquet")

from google.colab import drive
drive.mount('/content/drive')

!nvidia-smi

# ── Cell 2 — Install Unsloth ──────────────────────────────────────────────────
!pip install "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"
!pip install --no-deps trl peft accelerate bitsandbytes

import os

BASE       = '/content/mistral-finance-ft'
DATA_PATH  = '/content/finance_alpaca_clean.parquet'  # ← sits in /content/ directly
OUTPUT_DIR = f'{BASE}/outputs/adapter'
GGUF_DIR   = f'{BASE}/outputs/gguf'
MERGED_DIR = f'{BASE}/outputs/merged'

os.makedirs(f'{BASE}/data',    exist_ok=True)
os.makedirs(OUTPUT_DIR,        exist_ok=True)
os.makedirs(GGUF_DIR,          exist_ok=True)
os.makedirs(MERGED_DIR,        exist_ok=True)

# confirm
if os.path.exists(DATA_PATH):
    print(f"✓ Found parquet at {DATA_PATH}")
else:
    print(f"✗ Not found at {DATA_PATH}")

import os

os.makedirs('data2', exist_ok=True)

print('made')

import torch
import pandas as pd
from datasets import Dataset
from unsloth import FastLanguageModel
from trl import SFTTrainer
from transformers import TrainingArguments

print(f"Torch : {torch.__version__}")
print(f"CUDA : {torch.cuda.is_available()}")
print(f"GPU          : {torch.cuda.get_device_name(0)}")
print(f"VRAM         : {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")

df = pd.read_parquet(DATA_PATH)

print(f"Rows loaded : {len(df):,}")
print(f"Columns : {list(df.columns)}")
print(f"\nSample row:")
print(df['text'].iloc[0])

malformed = df[~df['text'].str.startswith('### Instruction:')]
print(f"Correctly formatted : {len(df) - len(malformed):,}")
print(f"Malformed rows      : {len(malformed)}")

# Check length distribution
df['word_count'] = df['text'].str.split().str.len()
print(f"\nWord count stats:")
print(df['word_count'].describe().round(1))

dataset = Dataset.from_pandas(df[['text']])


dataset = dataset.shuffle(seed=42).select(range(3000))

splits     = dataset.train_test_split(test_size=0.05, seed=42)
train_data = splits['train']
eval_data  = splits['test']

print(f"Total : 3,000")
print(f"Train : {len(train_data):,} rows")
print(f"Eval  : {len(eval_data):,} rows")

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "unsloth/Phi-3-mini-4k-instruct-bnb-4bit",
    max_seq_length=1024,
    dtype=None,
    load_in_4bit=True,
)

model = FastLanguageModel.get_peft_model(
    model,
    r=16,
    target_modules=[
        "q_proj", "k_proj", "v_proj", "o_proj",
        "gate_proj", "up_proj", "down_proj",
    ],
    lora_alpha = 32,
    lora_dropout=0.05,
    bias="none",
    use_gradient_checkpointing="unsloth",
    random_state=42,
)

model.print_trainable_parameters()

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=1,
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    gradient_accumulation_steps=4,
    eval_strategy="steps",
    eval_steps=500,
    save_strategy="steps",
    save_steps=500,
    save_total_limit=2,
    #warmup_ratio=0.03,
    warmup_steps=91,
    learning_rate=2e-4,
    fp16=True,
    logging_steps=50,
    optim="adamw_8bit",
    lr_scheduler_type="cosine",
    load_best_model_at_end=True,
    report_to="none",

)

trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=train_data,
    eval_dataset=eval_data,
    dataset_text_field="text",
    max_seq_length=256, # ← Increased to 1024
    args=training_args,
    packing=False,
)

trainer_stats = trainer.train()

print(f"\n✓ Training complete")
print(f"  Runtime  : {trainer_stats.metrics['train_runtime']/60:.1f} mins")
print(f"  Loss     : {trainer_stats.metrics['train_loss']:.4f}")
print(f"  Steps    : {trainer_stats.metrics['total_flos']:,.0f} FLOPS")

model.save_pretrained(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)
print(f"✓ Adapter saved → {OUTPUT_DIR}")


import os
for f in sorted(os.listdir(OUTPUT_DIR)):
    mb = os.path.getsize(f"{OUTPUT_DIR}/{f}") / 1e6
    print(f"  {f:<50} {mb:.1f} MB")

import shutil
from google.colab import files

shutil.make_archive("/content/phi3-finance-adapter", "zip", OUTPUT_DIR)
files.download("/content/phi3-finance-adapter.zip")

from google.colab import userdata
from huggingface_hub import login

HF_TOKEN = userdata.get('HF_TOKEN')
login(token=HF_TOKEN)

model.push_to_hub("priyalchugh06/phi3-finance", token=HF_TOKEN)
tokenizer.push_to_hub("priyalchugh06/phi3-finance", token=HF_TOKEN)
print("✓ Pushed → huggingface.co/your-username/phi3-finance")

FastLanguageModel.for_inference(model)
print("✓ Model in inference mode")

from transformers import TextStreamer

def ask(question, context="", max_tokens=200, temperature=0.7):
    if context.strip():
        prompt = f"### Instruction:\n{question}\n\n### Input:\n{context}\n\n### Response:\n"
    else:
        prompt = f"### Instruction:\n{question}\n\n### Response:\n"

    inputs = tokenizer(prompt, return_tensors="pt").to("cuda")

    streamer = TextStreamer(tokenizer, skip_prompt=True, skip_special_tokens=True)

    model.generate(
        **inputs,
        streamer=streamer,
        max_new_tokens=max_tokens,
        temperature=temperature,
        do_sample=True,
        pad_token_id=tokenizer.eos_token_id,
    )

# try it
ask("What is the difference between a Roth IRA and a traditional IRA?")