# -*- coding: utf-8 -*-
"""SFT+RL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aYwOJPeSxDy5-s2ccCUJLF8LbYJW0tqw
"""

pip install torch transformers datasets trl accelerate

from transformers import AutoTokenizer

model_name = "gpt2"
tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token

from datasets import Dataset

sft_data = Dataset.from_dict({
    "text": [
        "What is 2 + 3? 2 + 3 equals 5.",
        "What is 1 + 1? 1 + 1 equals 2."
    ]
})

def tokenize_sft(example):
  tokens = tokenizer(
      example["text"],
      truncation=True,
      padding="max_length",
      max_length=64,
  )

  tokens["labels"] = tokens["input_ids"].copy()
  return tokens

tokenized_sft = sft_data.map(tokenize_sft, remove_columns=['text'])

from transformers import(
    AutoModelForCausalLM,
    TrainingArguments,
    Trainer,
)

sft_model = AutoModelForCausalLM.from_pretrained(model_name)

sft_args = TrainingArguments(
    output_dir="./sft_model",
    per_device_train_batch_size=2,
    num_train_epochs=3,
    logging_steps=1,
    save_steps=10,
    report_to="none"
)

sft_trainer = Trainer(
    model=sft_model,
    args=sft_args,
    train_dataset=tokenized_sft,
    tokenizer=tokenizer,
)

sft_trainer.train()
sft_trainer.save_model("./sft_model")

#reward model

rm_data = Dataset.from_dict({
    "prompt": ["What is 2 + 3?"],
    "chosen": ["2 + 3 equals 5."],
    "rejected": ["I think it is 6."]
})

def tokenize_rm(example):
  chosen = tokenizer(
      example["prompt"] + " " + example["chosen"],
      truncation = True,
      padding = "max_length",
      max_length = 64,
  )

  rejected = tokenizer(
      example['prompt'] + " " + example["rejected"],
      truncation = True,
      padding = "max_length",
      max_length = 64,
  )

  return {
        "input_ids_chosen": chosen["input_ids"],
        "attention_mask_chosen": chosen["attention_mask"],
        "input_ids_rejected": rejected["input_ids"],
        "attention_mask_rejected": rejected["attention_mask"],
    }

tokenized_rm = rm_data.map(tokenize_rm, remove_columns= rm_data.column_names)

from transformers import AutoModelForSequenceClassification

reward_model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=1
)

import torch

def reward_data_collator(features):
    return {
        "input_ids_chosen": torch.tensor(
            [f["input_ids_chosen"] for f in features]
        ),
        "attention_mask_chosen": torch.tensor(
            [f["attention_mask_chosen"] for f in features]
        ),
        "input_ids_rejected": torch.tensor(
            [f["input_ids_rejected"] for f in features]
        ),
        "attention_mask_rejected": torch.tensor(
            [f["attention_mask_rejected"] for f in features]
        ),
    }

import torch
from transformers import Trainer

class RewardTrainer(Trainer):
    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        r_chosen = model(
            input_ids=inputs["input_ids_chosen"],
            attention_mask=inputs["attention_mask_chosen"],
        ).logits

        r_rejected = model(
            input_ids=inputs["input_ids_rejected"],
            attention_mask=inputs["attention_mask_rejected"],
        ).logits

        loss = -torch.log(torch.sigmoid(r_chosen - r_rejected)).mean()
        return (loss, None) if return_outputs else loss

rm_args = TrainingArguments(
    output_dir="./reward_model",
    per_device_train_batch_size=1,
    num_train_epochs=3,
    logging_steps=1,
    save_steps=10,
    report_to="none",
    remove_unused_columns=False,  # ← THIS IS THE FIX
)


rm_trainer = RewardTrainer(
    model=reward_model,
    args=rm_args,
    train_dataset=tokenized_rm,
    data_collator = reward_data_collator
)

rm_trainer.train()
rm_trainer.save_model("./reward_model")

#ppo
!pip install trl
from trl import PPOTrainer, PPOConfig
from transformers import AutoModelForCausalLM

policy_model = AutoModelForCausalLM.from_pretrained("sft_model", local_files_only=True)
ref_model = AutoModelForCausalLM.from_pretrained("sft_model", local_files_only=True)
reward_model = AutoModelForSequenceClassification.from_pretrained("reward_model", local_files_only=True)
value_model = AutoModelForCausalLM.from_pretrained("sft_model", local_files_only=True) # Initialize value model

from datasets import Dataset

ppo_dataset = Dataset.from_dict({
    "prompt": [
        "What is 2 + 3?",
        "What is 1 + 1?",
    ]
})

from trl import PPOTrainer, PPOConfig

ppo_config = PPOConfig(
    batch_size=1,
    learning_rate=1e-5,
    bf16=False,
    fp16=False,
)

ppo_trainer = PPOTrainer(
    ppo_config,    # 1. config (PPOConfig object)
    tokenizer,     # 2. processing_class (tokenizer object)
    policy_model,  # 3. model (policy model)
    ref_model,     # 4. ref_model (reference model)
    reward_model,  # 5. reward_model (reward model)
    ppo_dataset,   # 6. train_dataset (PPO training dataset)
    value_model    # 7. value_model (value model)
)

prompt = "What is 2 + 3?"
query = tokenizer(prompt, return_tensors="pt").input_ids

response = policy_model.generate(query, max_new_tokens=20)
response_text = tokenizer.decode(response[0], skip_special_tokens=True)

reward_inputs = tokenizer(
    prompt + " " + response_text,
    return_tensors="pt",
    truncation=True,
)
reward = reward_model(**reward_inputs).logits.squeeze()

ppo_trainer.step(
    queries=[query[0]],
    responses=[response[0]],
    rewards=[reward.detach()],
)